<?php  $db_data["quality"] = array (
  2 => 
  array (
    'id' => '3',
    'name' => 'small',
    'thmb_size' => '273',
    'thmb_qual' => '100',
    'photo_size' => '500',
    'photo_qual' => '85',
    'enabled' => 'true',
    'default' => 'true',
    'resize_if_bigger' => 'false',
    'square_thumbnails' => 'false',
    'resize_photo_to_fit' => 'both',
    'watermark_file' => '',
    'watermark_position' => 'RD',
    'thmb_sharp_use' => 'false',
    'thmb_sharp_amount' => '20',
    'thmb_sharp_radius' => '1',
    'thmb_sharp_treshold' => '0',
    'thmb_show_views' => 'true',
    'thmb_show_comments' => 'true',
    'thmb_show_votes' => 'false',
  ),
) ?>